{"name": "test_login_failed_invalid_data[case0]", "status": "passed", "parameters": [{"name": "case", "value": "{'user': '', 'passwd': '254992', 'check': '请输入手机号'}"}], "start": 1636516635156, "stop": 1636516636093, "uuid": "c5423876-39de-45c9-9a3a-ad6e36792fe0", "historyId": "f0bfd36e151bd6809e3bea92a4f95e89", "testCaseId": "98e067a681f547a2e44e78c948720b9e", "fullName": "TestCases.test_login.TestLogin#test_login_failed_invalid_data", "labels": [{"name": "epic", "value": "[epic]盛杰运营后台"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-OTOI92D"}, {"name": "thread", "value": "9592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}