{"name": "[TiTile]case 登录失败逆向场景", "status": "passed", "parameters": [{"name": "case", "value": "{'user': '13252254992', 'passwd': '', 'check': '请输入密码'}"}], "start": 1636516801437, "stop": 1636516802419, "uuid": "77bbbc29-493b-47bd-83bd-be983fc19d60", "historyId": "1352fcf7b98c3a086b04449cfbf3bcb3", "testCaseId": "98e067a681f547a2e44e78c948720b9e", "fullName": "TestCases.test_login.TestLogin#test_login_failed_invalid_data", "labels": [{"name": "epic", "value": "[epic]盛杰运营后台"}, {"name": "story", "value": "[Story]用户根据用户名密码登录系统"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-OTOI92D"}, {"name": "thread", "value": "14180-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}