{"name": "[TiTile]case 登录失败逆向场景", "status": "passed", "description": "登录测试用例 执行人：李某", "parameters": [{"name": "case", "value": "{'user': '', 'passwd': '254992', 'check': '请输入手机号'}"}], "start": 1636521221364, "stop": 1636521222320, "uuid": "478cd48f-b578-4da8-b88b-6e62eed8d0bb", "historyId": "f0bfd36e151bd6809e3bea92a4f95e89", "testCaseId": "98e067a681f547a2e44e78c948720b9e", "fullName": "TestCases.test_login.TestLogin#test_login_failed_invalid_data", "labels": [{"name": "epic", "value": "[epic]盛杰运营后台"}, {"name": "story", "value": "[Story]用户根据用户名密码登录系统"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-OTOI92D"}, {"name": "thread", "value": "9080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}